### PR TITLE
explain that label has to exist

### PR DESCRIPTION
**Pull request by Borda**
add an explanation about existing label which is not clear and the error message does not help as eg other bots creates such label if it does not exists yet

### CODE REVIEW

**Comment by Borda** [comment]
@mschilde mind check this simple explanation? 🐰

**Comment by Borda** [comment]
@mschilde ^^

**Comment by Borda** [comment]
@mschilde mind check this simple explanation? 🐰

**Review by prince-chrismc — APPROVED** [review]

**Comment by Borda** [comment]
Hi @mschilde may I get your review on this simple edit?

**Comment by mschilde** [comment]
sorry for the delay

**Pull request merged**
